import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import getCurrentUser from "@/app/actions/getCurrentUser";
import Script from "next/script";
import ToastProvider from "@/components/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar currentUser={currentUser} />
        <ToastProvider />

        {children}
        <Script src="//dapi.kakao.com/v2/maps/sdk.js?appkey=41932fe3aa8b24a6a90486b37d89f167&libraries=services,clusterer&autoload=false" />
      </body>
    </html>
  );
}
